apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudops-demo
  template:
    metadata:
      labels:
        app: cloudops-demo
    spec:
      imagePullSecrets:
        - name: aliyun-acr-secret
      containers:
        - name: cloudops-demo
          image: crpi-38urml8fe00gm6pl.cn-shenzhen.personal.cr.aliyuncs.com/cloudopsczq/cloudops-demo:30
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 20
