apiVersion: v1
kind: Service
metadata:
  name: cloudops-demo-service
spec:
  selector:
    app: cloudops-demo
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30426
  type: NodePort
